// vue_ecsite/vue_src/views/Login.vue
<template>
  <div class="top-wrapper">
    <div class="container">
      <div class="row login-page">
        <div class="col s12 z-depth-6 card-panel">
          <div class="error">{{ errorMessage }}</div>
          <form class="login-form" action="employeeList.html">
            <div class="row"></div>
            <div class="row">
              <div class="input-field col s12">
                <i class="material-icons prefix">mail_outline</i>
                <span class="error">{{ mailAddressError }}</span>
                <input
                  class="validate"
                  id="mailAddress"
                  type="email"
                  v-model="mailAddress"
                />
                <label for="mailAddress" data-error="wrong" data-success="right"
                  >メールアドレス</label
                >
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <i class="material-icons prefix">lock_outline</i>
                <span class="error">{{ passwordError }}</span>
                <input id="password" type="password" v-model="password" />
                <label for="password">パスワード</label>
              </div>
            </div>
            <div class="row login-btn">
              <button class="btn" type="button" v-on:click="login">
                <span>ログイン</span>
              </button>
            </div>
            <div class="row">
              <div class="input-field col s6 m6 l6">
                <p class="margin medium-small">
                  <router-link to="/registerUser"
                    >ユーザー登録はこちら</router-link
                  >
                </p>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import { User } from "../types/User";
import axios from "axios";
@Component
export default class XXXComponent extends Vue {
  // メールアドレス
  private mailAddress = "";
  // パスワード
  private password = "";
  // ログイン時のエラーメッセージ
  private errorMessage = "";
  // メールアドレスのエラーメッセージ
  private mailAddressError = "";
  // パスワードのエラーメッセージ
  private passwordError = "";

  /**
   * ログインをする.
   * @returns Promiseオブジェクト
   */
  async login(): Promise<void> {
    // エラーチェック
    let existError = false;
    if (this.mailAddress === "") {
      this.mailAddressError = "メールアドレスが入力されていません";
      existError = true;
    }
    if (this.password === "") {
      this.passwordError = "パスワードが入力されていません";
      existError = true;
    }
    if (existError === true) {
      return;
    }

    const response = await axios.post(
      "http://153.127.48.168:8080/ecsite-api/user/login",
      {
        email: this.mailAddress,
        password: this.password,
      }
    );
    console.dir("response:" + JSON.stringify(response));
    if (response.data.status === "success") {
      //ログイン状態にする
      this.$store.commit("login");
      this.$router.push("/itemList");
      // reponseからのユーザー情報の取得
      const loginUserInfo = new User(
        response.data.responseMap.user.id,
        response.data.responseMap.user.name,
        response.data.responseMap.user.email,
        response.data.responseMap.user.password,
        response.data.responseMap.user.zipcode,
        response.data.responseMap.user.address,
        response.data.responseMap.user.telephone
      );
      console.dir("loginUserInfo:" + JSON.stringify(loginUserInfo));
      // ユーザーをセットする
      this.$store.commit("setUserInfo", loginUserInfo);
    } else {
      this.errorMessage = "ログインに失敗しました";
    }
  }
}
</script>

<style scoped></style>

// src/pages/Login.tsx
/* eslint-disable no-lone-blocks */
import React, { useContext } from "react";
import axios from "axios";
import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { InputLogin } from "../components/inputLogin";
import Button from "@material-ui/core/Button";
import { statusContext } from "../components/providers/statusContext";
// useEffectを使ったログイン機能;
export const Login = () => {
  const navigate = useNavigate();

  const [loginErrorMessage, setloginErrorMessage] = useState("");
  const [mailAddress, setmailAddress] = useState("");
  const [password, setpassword] = useState("");
  const auth = useContext(statusContext);

  const submitLogin = async () => {
    console.log(mailAddress, password);
    setloginErrorMessage(() => "");
    const response = await axios.post(
      "http://153.127.48.168:8080/ecsite-api/user/login",
      { mailAddress: mailAddress, password: password }
    );
    const status = response.data.status;
    console.dir("responce:" + JSON.stringify(response));
    if (status === "success") {
      console.log("成功");
      auth?.setstatusCheck(true);
      navigate("/ItemList");
    } else if (status === "error") {
      alert("メールアドレス、またはパスワードが間違っています");
    } else {
      alert("メールアドレス、パスワードを記入してください");
    }
  };

  return (
    <div>
      <div className="top-wrapper">
        <div className="container">
          <div className="row login-page">
            <div className="col s12 z-depth-6 card-panel"></div>
            <form>
              <h1>ログイン画面 </h1>
              <label htmlFor="mailAddress">メールアドレス:</label>
              <input
                type="text"
                className="mailAddress"
                id="mailAddress"
                onChange={(event) => setmailAddress(() => event.target.value)}
              />
              <br></br>
              <label htmlFor="password">パスワード:</label>
              <input
                type="text"
                className="password"
                id="password"
                onChange={(event) => setpassword(() => event.target.value)}
              />
              <div className="row login-btn">
                <Button className="btn" onClick={submitLogin}>
                  ログインする
                </Button>
                <Button
                  className="btn"
                  onClick={() => navigate("/registerUser")}
                >
                  ユーザー登録へ戻る
                </Button>
              </div>
            </form>
          </div>{" "}
        </div>{" "}
      </div>{" "}
    </div>
  );
};

// export function Login() {
//   // eslint-disable-next-line react-hooks/rules-of-hooks
//   const navigate = useNavigate();

//   return (
//     <div>
//       <h3>ログイン画面</h3>
//       {/* 入力フォームのimport */}
//       {/* <InputLogin /> */}
//       {/* ログイン切り替えボタンのimport */}
//       <StatusButton />

//       <button className="btn" onClick={() => navigate("/content")}>
//         ユーザー登録
//       </button>

//       <div>
//         <Button color="inherit" onClick={() => navigate("/")}>
//           Topページに戻る
//         </Button>
//       </div>
//     </div>
//   );
// }
