// vue_ecsite/vue_src/views/Login.vue
<template>
  <div class="top-wrapper">
    <div class="container">
      <div class="row login-page">
        <div class="col s12 z-depth-6 card-panel">
          <div class="error">{{ errorMessage }}</div>
          <form class="login-form" action="employeeList.html">
            <div class="row"></div>
            <div class="row">
              <div class="input-field col s12">
                <i class="material-icons prefix">mail_outline</i>
                <span class="error">{{ mailAddressError }}</span>
                <input
                  class="validate"
                  id="mailAddress"
                  type="email"
                  v-model="mailAddress"
                />
                <label for="mailAddress" data-error="wrong" data-success="right"
                  >メールアドレス</label
                >
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <i class="material-icons prefix">lock_outline</i>
                <span class="error">{{ passwordError }}</span>
                <input id="password" type="password" v-model="password" />
                <label for="password">パスワード</label>
              </div>
            </div>
            <div class="row login-btn">
              <button class="btn" type="button" v-on:click="login">
                <span>ログイン</span>
              </button>
            </div>
            <div class="row">
              <div class="input-field col s6 m6 l6">
                <p class="margin medium-small">
                  <router-link to="/registerUser"
                    >ユーザー登録はこちら</router-link
                  >
                </p>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import { User } from "../types/User";
import axios from "axios";
@Component
export default class XXXComponent extends Vue {
  // メールアドレス
  private mailAddress = "";
  // パスワード
  private password = "";
  // ログイン時のエラーメッセージ
  private errorMessage = "";
  // メールアドレスのエラーメッセージ
  private mailAddressError = "";
  // パスワードのエラーメッセージ
  private passwordError = "";

  /**
   * ログインをする.
   * @returns Promiseオブジェクト
   */
  async login(): Promise<void> {
    // エラーチェック
    let existError = false;
    if (this.mailAddress === "") {
      this.mailAddressError = "メールアドレスが入力されていません";
      existError = true;
    }
    if (this.password === "") {
      this.passwordError = "パスワードが入力されていません";
      existError = true;
    }
    if (existError === true) {
      return;
    }

    const response = await axios.post(
      "http://153.127.48.168:8080/ecsite-api/user/login",
      {
        email: this.mailAddress,
        password: this.password,
      }
    );
    console.dir("response:" + JSON.stringify(response));
    if (response.data.status === "success") {
      //ログイン状態にする
      this.$store.commit("login");
      this.$router.push("/itemList");
      // reponseからのユーザー情報の取得
      const loginUserInfo = new User(
        response.data.responseMap.user.id,
        response.data.responseMap.user.name,
        response.data.responseMap.user.email,
        response.data.responseMap.user.password,
        response.data.responseMap.user.zipcode,
        response.data.responseMap.user.address,
        response.data.responseMap.user.telephone
      );
      console.dir("loginUserInfo:" + JSON.stringify(loginUserInfo));
      // ユーザーをセットする
      this.$store.commit("setUserInfo", loginUserInfo);
    } else {
      this.errorMessage = "ログインに失敗しました";
    }
  }
}
</script>

<style scoped></style>

// src/pages/Login.jsx
import { useState, useEffect } from "react";
import React from "react";
import { Link } from "react-router-dom";
import axios from "axios";

export const Login = () => {
  const [loginData, setloginData] = useState({
    mailAddress: "",
    password: "",
  });

  const handleChange = (event) => {
    const newLoginData = { ...loginData };
    newLoginData[event.target.id] = event.target.value;
    setloginData(newLoginData);
    console.log(newLoginData);
    event.preventDefault();
  };

  useEffect(() => {
    const submit = async () => {
      await fetch(
        axios
          .post("http://153.127.48.168:8080/ecsite-api/user/login", {
            setloginData,
          })
          //   本来ならここにif文でres=successが入る
          .then((res) => {
            console.log("success");
            console.log(res.loginData);
            setloginData(loginData.mailAddress, loginData.password);
          })
          .catch((error) => {
            console.log(error);
          })
      );
      submit();
    };
  });

  return (
    <div>
      <div className="top-wrapper">
        <div className="container">
          <div className="row login-page">
            <div className="col s12 z-depth-6 card-panel"></div>
            <form onSubmit={(event) => setloginData(event)}>
              <h1>ログイン画面 </h1>
              <label htmlFor="mailAddress">メールアドレス:</label>
              <input
                type="text"
                className="mailAddress"
                id="mailAddress"
                onChange={(event) => handleChange(event)}
                value={setloginData.mailAddress}
              />
              <br></br>
              <label htmlFor="password">パスワード:</label>
              <input
                type="text"
                className="password"
                id="password"
                onChange={handleChange}
                value={setloginData.password}
              />
              <div className="row login-btn">
                <button
                  className="btn"
                  type="submit"
                  //   onClick={() => setloginData()}
                >
                  ログイン
                </button>
                <Link to="registerUser">ユーザー登録</Link>
              </div>
            </form>
          </div>{" "}
        </div>{" "}
      </div>{" "}
    </div>
  );
};
