// src/pages/ItemDetail.tsx
import axios from "axios";
import React, { useState, useEffect, useContext } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { Item } from "../types/Item";
import { Topping } from "../types/Topping";
import { cartListContext } from "../components/providers/CartListProvider";
import { OrderItem } from "../types/OrderItem";

export const ItemDetail = () => {
  // routerからitemidを取得する
  const { itemId } = useParams();

  useEffect(() => {
    axios
      .get("http://153.127.48.168:8080/ecsite-api/item/" + itemId)
      .then((response) => {
        setItem(response.data.item);
        setToppingList(response.data.item.toppingList);
      });
  }, [itemId]);

  //商品のトッピング一覧
  const [toppingList, setToppingList] = useState<Array<Topping>>();

  const priceMArray = toppingList?.map((topping, index) => {
    return topping.priceM;
  });

  console.log(priceMArray);

  const priceM = priceMArray?.map((price, index) => {
    return price.valueOf();
  });

  console.log(priceM);

  // 商品一覧
  const [item, setItem] = useState<Item>({
    deleted: false,
    description: "",
    id: 0,
    imagePath: "",
    name: "",
    priceL: 0,
    priceM: 0,
    toppingList: [],
    type: "",
  });

  // サイズの初期値
  const [size, setSize] = useState<string>("M");
  // サイズ選択
  const [hasSize, setHasSize] = useState(true);
  //チェックボックス変更するメソッド
  const changeSize = (e: React.ChangeEvent<HTMLInputElement>) => {
    setHasSize(!hasSize);
    setSize(() => e.target.value);
  };

  // 数量
  const [quantity, setQuantity] = useState<number>(100);

  //ショッピングカート
  const cart = useContext(cartListContext);

  // カートにいれる
  const pushInCartList = () => {
    const orderItem: OrderItem = {
      id: 1, //仮
      itemId: item.id,
      orderId: 1, //仮）オーダーのステートを作成し、そのIDを取ってくる
      quantity: quantity,
      size: size,
      item: item,
      orderToppingList: [],
    };
    cart?.setCartList([...cart.cartList, orderItem]);
    navigate("/CartList/");
  };
  //画面遷移のメソッド化
  const navigate = useNavigate();

  //合計金額
  const totalPrices = (item.priceM + 200) * quantity;

  // トッピングの取得
  // const getToppingValue = (e: React.ChangeEvent<HTMLInputElement>) => {
  //   setToppingList(() => e.target.value);
  // };

  return (
    <div>
      <h1>{item?.name}</h1>
      <img className="itemImage" src={item?.imagePath} alt="test" />
      <p>{item?.description}</p>
      <input
        id="M"
        name="size"
        type="radio"
        value="M"
        checked={hasSize}
        onChange={changeSize}
      />
      <label htmlFor="M"> M {item?.priceM}円</label>
      <input
        id="L"
        name="size"
        type="radio"
        value="L"
        checked={!hasSize}
        onChange={changeSize}
      />
      <label htmlFor="L">L {item?.priceL}円</label>
      <div>トッピング： 1つにつき Ｍ 200円(税抜) Ｌ 300 円(税抜)</div>
      {toppingList?.map((topping, index) => {
        return (
          <div>
            <label key={index}>
              <input
                type="checkbox"
                // onChange={(e) => setToppingList(e.target.value)}
                value={topping.name}
              />
              <span>{topping.name}</span>
            </label>
          </div>
        );
      })}
      <div>
        ; 数量
        <select
          className="quantity"
          name="quantity"
          id="pizzaQuantity"
          onChange={(e) => setQuantity(Number(e.target.value))}
          defaultValue="1"
        >
          <option value="1">1</option>
          <option value="2">2</option>
          <option value="3">3</option>
          <option value="4">4</option>
          <option value="5">5</option>
          <option value="6">6</option>
          <option value="7">7</option>
          <option value="8">8</option>
          <option value="9">9</option>
          <option value="10">10</option>
          <option value="11">11</option>
          <option value="12">12</option>
        </select>
      </div>
      <div>この商品金額：{totalPrices}円（税抜）</div>
      <div>
        <button
          onClick={() => {
            pushInCartList();
          }}
        >
          カートに入れる
        </button>
      </div>
      <div>
        <button
          onClick={() => {
            navigate("/itemList/");
          }}
        >
          商品一覧に戻る
        </button>
      </div>
    </div>
  );
};

// vue_ecsite/vue_src/views/ItemDetail.vue
<template>
  <div>
    <div class="top-wrapper">
      <div class="background">
        <div class="container">
          <h1 class="page-title">{{ currentItem.name }}</h1>
          <div class="row">
            <div class="row item-detail">
              <div class="item-icon">
                <img v-bind:src="currentItem.imagePath" />
              </div>
              <div class="item-intro">{{ currentItem.description }}</div>
            </div>
            <div class="row item-size">
              <div class="item-hedding">サイズ</div>
              <div>
                <label>
                  <input
                    id="size-m"
                    name="size"
                    type="radio"
                    value="M"
                    v-on:change="calcSubTotalPrice"
                    v-model="size"
                  />
                  <span>
                    &nbsp;<span class="price">Ｍ</span>&nbsp;&nbsp;{{
                      currentItem.formatPriceM
                    }}円(税抜)</span
                  >
                </label>
                <label>
                  <input
                    id="size-l"
                    name="size"
                    type="radio"
                    value="L"
                    v-on:change="calcSubTotalPrice"
                    v-model="size"
                  />
                  <span>
                    &nbsp;<span class="price">Ｌ</span>&nbsp;&nbsp;{{
                      currentItem.formatPriceL
                    }}円(税抜)</span
                  >
                </label>
              </div>
            </div>
            <div class="row item-toppings">
              <div class="item-hedding">
                トッピング：&nbsp;1つにつき
                <span>&nbsp;Ｍ&nbsp;</span>&nbsp;&nbsp;200円(税抜)
                <span>&nbsp;Ｌ</span>&nbsp;&nbsp;300円(税抜)
              </div>
              <label
                class="item-topping"
                v-for="topping of currentItem.toppingList"
                v-bind:key="topping.id"
              >
                <input
                  type="checkbox"
                  v-on:change="calcSubTotalPrice"
                  v-bind:value="topping"
                  v-model="checkedToppingList"
                />
                <span>{{ topping.name }}</span>
              </label>
            </div>
          </div>
          <div class="row item-quantity">
            <div class="item-hedding item-hedding-quantity">数量</div>
            <div class="item-quantity-selectbox">
              <div class="input-field col s12">
                <select
                  class="browser-default"
                  v-model="quantity"
                  v-on:change="calcSubTotalPrice"
                >
                  <option value="" disabled selected>選択して下さい</option>
                  <option value="1">1</option>
                  <option value="2">2</option>
                  <option value="3">3</option>
                  <option value="4">4</option>
                  <option value="5">5</option>
                  <option value="6">6</option>
                  <option value="7">7</option>
                  <option value="8">8</option>
                  <option value="9">9</option>
                  <option value="10">10</option>
                  <option value="11">11</option>
                  <option value="12">12</option>
                </select>
              </div>
            </div>
          </div>
          <div class="row item-total-price">
            <span
              >この商品金額：{{
                itemSubTotalPrice.toLocaleString()
              }}円(税抜)</span
            >
          </div>
          <div class="row item-cart-btn">
            <button class="btn" type="button" v-on:click="putInCart">
              <span>カートに入れる</span>
            </button>
          </div>
          <div class="row item-cart-btn">
            <button class="btn" type="button" v-on:click="backToItemList">
              <span>商品一覧に戻る</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import { Item } from "@/types/Item";
import { Topping } from "@/types/Topping";
import axios from "axios";
@Component
export default class XXXComponent extends Vue {
  private currentItem = new Item(
    0,
    "",
    "",
    "",
    0,
    0,
    "",
    false,
    new Array<Topping>()
  );
  private checkedToppingList = Array<Topping>();
  private size = "M";
  private quantity = 1; // 初期値を１にしないと計算式が成り立たない
  private itemSubTotalPrice = 0;

  /**
   *WebAPIから１件の商品情報を取得する.
   *@returns Promiseオブジェクト
   */
  async created(): Promise<void> {
    try {
      // 商品を1件取得する
      const itemId = Number(this.$route.params.id);
      const responce = await axios.get(
        "http://153.127.48.168:8080/ecsite-api/item/" + itemId
      );
      console.dir("responce:" + JSON.stringify(responce));
      let responceItem = responce.data.item;
      this.currentItem = new Item(
        responceItem.id,
        responceItem.type,
        responceItem.name,
        responceItem.description,
        responceItem.priceM,
        responceItem.priceL,
        responceItem.imagePath,
        responceItem.deleted,
        responceItem.toppingList
      );

      // トッピング一覧を取得する
      const responce2 = await axios.get(
        "http://153.127.48.168:8080/ecsite-api/item/toppings/aloha"
      );
      console.dir("responce:" + JSON.stringify(responce2));
      // 空の配列を作成しToppingオブジェクトをpushする
      let toppingList = new Array<Topping>();
      for (const topping of responce2.data.toppings) {
        toppingList.push(
          new Topping(
            topping.id,
            topping.type,
            topping.name,
            topping.priceM,
            topping.priceL
          )
        );
      }
      this.currentItem.toppingList = toppingList;
      this.itemSubTotalPrice = responceItem.priceM;
    } catch (e) {
      console.log(e);
      this.$router.push("/404error");
      return;
    }
  }
  /**
   * 商品をカートに入れる(CartListに画面遷移する).
   */
  putInCart(): void {
    this.$store.commit("putInCart", {
      item: this.currentItem,
      topping: this.checkedToppingList,
      quantity: this.quantity,
      size: this.size,
    });
    this.$router.push("/cartList");
  }
  backToItemList(): void {
    this.$router.push("/itemList");
  }
  /**
   * 税抜き金額を計算する.
   */
  calcSubTotalPrice(): void {
    let toppingPrice = 0;
    let sizePrice = 0;
    if (this.size === "M") {
      sizePrice = this.currentItem.priceM;
    }
    if (this.size === "L") {
      sizePrice = this.currentItem.priceL;
    }
    for (let topping of this.checkedToppingList) {
      if (this.size === "M") {
        toppingPrice += topping.priceM;
      }
      if (this.size === "L") {
        toppingPrice += topping.priceL;
      }
    }
    this.itemSubTotalPrice = (toppingPrice + sizePrice) * this.quantity;
  }
}
</script>

<style scoped></style>
